data:
  dataset: voxel
  dataset_dir: out/dataset/mug_v2
  dataset_len: 4000
method: object_model
training:
  out_dir: out/models/rotation/cnn_model_v1/
  learning_rate: 0.001
  print_every: 10
  epochs: 10000
  min_epochs: 400
  max_epochs_without_improving: 20
  batch_size: 16
  val_batch_size: 16
  shuffle: true
  loss_weights:
    reconstruction: 1.0
model:
  type: cnnnet