data:
  dataset: voxel
  dataset_dir: out/dataset/mug_v2
  dataset_len: 4000
method: object_model
training:
  out_dir: out/models/rotation/kp_model_v2
  learning_rate: 0.001
  print_every: 10
  epochs: 10000
  min_epochs: 500
  max_epochs_without_improving: 20
  batch_size: 8
  val_batch_size: 8
  shuffle: true
  loss_weights:
    reconstruction: 1.0
    separation: 0.1
    consistency: 0.1
model:
  type: keypointnet
  k: 32