data:
  dataset: voxel
  dataset_dir: out/dataset/mug
  transforms:
    - type: scale_pc
      in_key: point_cloud
      out_key: point_cloud_1
      scale_key: scale_1
    - type: tf_pc
      in_key: point_cloud_1
      out_key: point_cloud_1
      rot_key: rot_1
    - type: pc_to_voxel
      in_key: point_cloud_1
      out_key: voxel_1
      voxel_size: 32
    - type: scale_pc
      in_key: point_cloud
      out_key: point_cloud_2
      scale_key: scale_2
    - type: tf_pc
      in_key: point_cloud_2
      out_key: point_cloud_2
      rot_key: rot_2
    - type: pc_to_voxel
      in_key: point_cloud_2
      out_key: voxel_2
      voxel_size: 32
method: object_model
training:
  out_dir: out/models/test
  learning_rate: 0.0001
  print_every: 10
  epochs: 500
  min_epochs: 100
  max_epochs_without_improving: 10
  batch_size: 32
  val_batch_size: 32
  shuffle: true
  loss_weights:
    reconstruction: 1.0